import 'dotenv/config';
import { connectDB } from '../config/database';
import Country from '../models/Country';

function slugify(text: string): string {
  return text.toLowerCase().trim().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
}

const countries = [
  { name: 'Afghanistan',                              flag: 'af', code: 'AF', description: 'Mountainous South Asian country with a rich cultural heritage.' },
  { name: 'Albania',                                  flag: 'al', code: 'AL', description: 'Balkan nation known for scenic coasts and rugged mountains.' },
  { name: 'Algeria',                                  flag: 'dz', code: 'DZ', description: "Africa's largest country, dominated by the Sahara Desert." },
  { name: 'Andorra',                                  flag: 'ad', code: 'AD', description: 'Small Pyrenean principality between France and Spain.' },
  { name: 'Angola',                                   flag: 'ao', code: 'AO', description: 'Resource-rich Southern African nation on the Atlantic coast.' },
  { name: 'Antigua and Barbuda',                      flag: 'ag', code: 'AG', description: 'Caribbean island nation famous for beaches and tourism.' },
  { name: 'Argentina',                                flag: 'ar', code: 'AR', description: 'Large South American country known for tango and Patagonia.' },
  { name: 'Armenia',                                  flag: 'am', code: 'AM', description: 'Historic Caucasus nation known for ancient Christian heritage.' },
  { name: 'Austria',                                  flag: 'at', code: 'AT', description: 'Alpine European country famous for music and culture.' },
  { name: 'Azerbaijan',                               flag: 'az', code: 'AZ', description: 'Caspian nation blending European and Asian influences.' },
  { name: 'Bahamas',                                  flag: 'bs', code: 'BS', description: 'Tropical archipelago known for crystal-clear waters and resorts.' },
  { name: 'Bahrain',                                  flag: 'bh', code: 'BH', description: 'Gulf island kingdom and regional financial center.' },
  { name: 'Bangladesh',                               flag: 'bd', code: 'BD', description: 'Densely populated nation with fertile river deltas.' },
  { name: 'Barbados',                                 flag: 'bb', code: 'BB', description: 'Caribbean island known for beaches and vibrant culture.' },
  { name: 'Belarus',                                  flag: 'by', code: 'BY', description: 'Eastern European country with forests and historic cities.' },
  { name: 'Belgium',                                  flag: 'be', code: 'BE', description: 'European nation known for chocolates, waffles, and EU institutions.' },
  { name: 'Belize',                                   flag: 'bz', code: 'BZ', description: 'Central American country featuring reefs and rainforests.' },
  { name: 'Benin',                                    flag: 'bj', code: 'BJ', description: 'West African nation with rich cultural and historical traditions.' },
  { name: 'Bhutan',                                   flag: 'bt', code: 'BT', description: 'Himalayan kingdom focused on happiness and sustainability.' },
  { name: 'Bolivia',                                  flag: 'bo', code: 'BO', description: 'Landlocked nation with diverse landscapes and indigenous heritage.' },
  { name: 'Bosnia and Herzegovina',                   flag: 'ba', code: 'BA', description: 'Balkan country rich in history and cultural diversity.' },
  { name: 'Botswana',                                 flag: 'bw', code: 'BW', description: 'Southern African nation famous for wildlife and safaris.' },
  { name: 'Brazil',                                   flag: 'br', code: 'BR', description: 'Largest South American country, home to the Amazon.' },
  { name: 'Brunei Darussalam',                        flag: 'bn', code: 'BN', description: 'Wealthy Southeast Asian sultanate rich in oil reserves.' },
  { name: 'Bulgaria',                                 flag: 'bg', code: 'BG', description: 'Balkan nation known for mountains and Black Sea coast.' },
  { name: 'Burkina Faso',                             flag: 'bf', code: 'BF', description: 'Landlocked West African country with strong cultural traditions.' },
  { name: 'Burundi',                                  flag: 'bi', code: 'BI', description: 'Small East African nation bordering Lake Tanganyika.' },
  { name: 'Cabo Verde',                               flag: 'cv', code: 'CV', description: 'Atlantic island nation with volcanic landscapes and Creole culture.' },
  { name: 'Cambodia',                                 flag: 'kh', code: 'KH', description: 'Southeast Asian country home to Angkor Wat.' },
  { name: 'Cameroon',                                 flag: 'cm', code: 'CM', description: 'Diverse Central African nation known as "Africa in Miniature."' },
  { name: 'Central African Republic',                 flag: 'cf', code: 'CF', description: 'Landlocked nation rich in wildlife and natural resources.' },
  { name: 'Chad',                                     flag: 'td', code: 'TD', description: 'Saharan African country with varied desert and savanna landscapes.' },
  { name: 'Chile',                                    flag: 'cl', code: 'CL', description: "Long Pacific nation stretching along South America's west coast." },
  { name: 'China',                                    flag: 'cn', code: 'CN', description: "World's most populous nation with ancient history and innovation." },
  { name: 'Colombia',                                 flag: 'co', code: 'CO', description: 'Diverse South American country known for coffee and culture.' },
  { name: 'Comoros',                                  flag: 'km', code: 'KM', description: 'Indian Ocean island nation with volcanic origins.' },
  { name: 'Congo',                                    flag: 'cg', code: 'CG', description: 'Central African country covered by extensive tropical rainforests.' },
  { name: 'Cook Islands',                             flag: 'ck', code: 'CK', description: 'South Pacific islands known for lagoons and coral reefs.' },
  { name: 'Costa Rica',                               flag: 'cr', code: 'CR', description: 'Eco-friendly nation renowned for biodiversity and nature tourism.' },
  { name: "Côte d'Ivoire",                            flag: 'ci', code: 'CI', description: 'West African country and leading global cocoa producer.' },
  { name: 'Croatia',                                  flag: 'hr', code: 'HR', description: 'Adriatic nation famous for historic towns and coastline.' },
  { name: 'Cuba',                                     flag: 'cu', code: 'CU', description: 'Caribbean island known for culture, music, and history.' },
  { name: 'Cyprus',                                   flag: 'cy', code: 'CY', description: 'Mediterranean island blending European and Middle Eastern influences.' },
  { name: 'Czechia',                                  flag: 'cz', code: 'CZ', description: 'Central European nation known for castles and Prague.' },
  { name: "Democratic People's Republic of Korea",    flag: 'kp', code: 'KP', description: 'East Asian nation occupying northern Korean Peninsula.' },
  { name: 'Democratic Republic of the Congo',         flag: 'cd', code: 'CD', description: 'Vast African nation with rich minerals and rainforests.' },
  { name: 'Denmark',                                  flag: 'dk', code: 'DK', description: 'Scandinavian country known for quality of life and design.' },
  { name: 'Djibouti',                                 flag: 'dj', code: 'DJ', description: 'Strategic Horn of Africa nation with key maritime routes.' },
  { name: 'Dominica',                                 flag: 'dm', code: 'DM', description: 'Caribbean island nation known for lush rainforests and nature.' },
  { name: 'Dominican Republic',                       flag: 'do', code: 'DO', description: 'Caribbean nation famous for beaches, resorts, and culture.' },
  { name: 'Ecuador',                                  flag: 'ec', code: 'EC', description: 'South American country home to the Galapagos Islands.' },
  { name: 'Egypt',                                    flag: 'eg', code: 'EG', description: 'Ancient civilization centered around the Nile River.' },
  { name: 'El Salvador',                              flag: 'sv', code: 'SV', description: 'Central American nation known for volcanoes and surfing.' },
  { name: 'Equatorial Guinea',                        flag: 'gq', code: 'GQ', description: 'Oil-rich Central African country with mainland and islands.' },
  { name: 'Eritrea',                                  flag: 'er', code: 'ER', description: 'Red Sea nation known for highlands and colonial architecture.' },
  { name: 'Estonia',                                  flag: 'ee', code: 'EE', description: 'Baltic nation recognized for digital innovation and history.' },
  { name: 'Eswatini',                                 flag: 'sz', code: 'SZ', description: 'Southern African kingdom preserving strong cultural traditions.' },
  { name: 'Ethiopia',                                 flag: 'et', code: 'ET', description: 'Historic African nation known for ancient heritage and highlands.' },
  { name: 'Fiji',                                     flag: 'fj', code: 'FJ', description: 'Pacific island nation famous for beaches and coral reefs.' },
  { name: 'Finland',                                  flag: 'fi', code: 'FI', description: 'Nordic country known for lakes, forests, and innovation.' },
  { name: 'Gabon',                                    flag: 'ga', code: 'GA', description: 'Central African country rich in rainforests and wildlife.' },
  { name: 'Gambia',                                   flag: 'gm', code: 'GM', description: 'Small West African nation centered on the Gambia River.' },
  { name: 'Georgia',                                  flag: 'ge', code: 'GE', description: 'Caucasus nation known for mountains, wine, and history.' },
  { name: 'Ghana',                                    flag: 'gh', code: 'GH', description: 'Stable West African nation known for gold and cocoa.' },
  { name: 'Greece',                                   flag: 'gr', code: 'GR', description: 'Birthplace of democracy with thousands of scenic islands.' },
  { name: 'Grenada',                                  flag: 'gd', code: 'GD', description: 'Caribbean island nation known as the Spice Isle.' },
  { name: 'Guatemala',                                flag: 'gt', code: 'GT', description: 'Central American country rich in Mayan heritage.' },
  { name: 'Guinea',                                   flag: 'gn', code: 'GN', description: 'West African nation rich in mineral resources.' },
  { name: 'Guinea-Bissau',                            flag: 'gw', code: 'GW', description: 'Coastal West African nation with island archipelagos.' },
  { name: 'Guyana',                                   flag: 'gy', code: 'GY', description: 'English-speaking South American country with vast rainforests.' },
  { name: 'Haiti',                                    flag: 'ht', code: 'HT', description: 'Caribbean nation with vibrant culture and historic significance.' },
  { name: 'Honduras',                                 flag: 'hn', code: 'HN', description: 'Central American country known for biodiversity and ruins.' },
  { name: 'Hungary',                                  flag: 'hu', code: 'HU', description: 'Central European nation famous for Budapest and thermal baths.' },
  { name: 'Iceland',                                  flag: 'is', code: 'IS', description: 'Nordic island nation of volcanoes, glaciers, and geysers.' },
  { name: 'India',                                    flag: 'in', code: 'IN', description: 'Diverse South Asian nation with rich history and culture.' },
  { name: 'Indonesia',                                flag: 'id', code: 'ID', description: "World's largest archipelago with thousands of islands." },
  { name: 'Iran',                                     flag: 'ir', code: 'IR', description: 'Historic Middle Eastern nation rooted in Persian civilization.' },
  { name: 'Iraq',                                     flag: 'iq', code: 'IQ', description: "Ancient Mesopotamian land known as civilization's cradle." },
  { name: 'Ireland',                                  flag: 'ie', code: 'IE', description: 'Island nation known for green landscapes and heritage.' },
  { name: 'Israel',                                   flag: 'il', code: 'IL', description: 'Middle Eastern nation with deep historical and religious significance.' },
  { name: 'Italy',                                    flag: 'it', code: 'IT', description: 'European country famous for art, history, and cuisine.' },
  { name: 'Jamaica',                                  flag: 'jm', code: 'JM', description: 'Caribbean island renowned for reggae and tropical beauty.' },
  { name: 'Jordan',                                   flag: 'jo', code: 'JO', description: 'Middle Eastern kingdom home to the ancient city of Petra.' },
  { name: 'Kazakhstan',                               flag: 'kz', code: 'KZ', description: "World's largest landlocked country rich in natural resources." },
  { name: 'Kenya',                                    flag: 'ke', code: 'KE', description: 'East African nation famous for safaris and wildlife.' },
  { name: 'Kiribati',                                 flag: 'ki', code: 'KI', description: 'Pacific island nation spread across a vast ocean area.' },
  { name: 'Kuwait',                                   flag: 'kw', code: 'KW', description: 'Oil-rich Gulf nation with a modern economy.' },
  { name: 'Kyrgyzstan',                               flag: 'kg', code: 'KG', description: 'Mountainous Central Asian nation along the Silk Road.' },
  { name: 'Lao PDR',                                  flag: 'la', code: 'LA', description: 'Landlocked Southeast Asian country along the Mekong River.' },
  { name: 'Latvia',                                   flag: 'lv', code: 'LV', description: 'Baltic nation known for forests and sandy coastlines.' },
  { name: 'Lebanon',                                  flag: 'lb', code: 'LB', description: 'Mediterranean country with rich cultural and historical heritage.' },
  { name: 'Lesotho',                                  flag: 'ls', code: 'LS', description: 'Mountain kingdom completely surrounded by South Africa.' },
  { name: 'Liberia',                                  flag: 'lr', code: 'LR', description: 'West African nation founded by freed American settlers.' },
  { name: 'Libya',                                    flag: 'ly', code: 'LY', description: 'North African country dominated by desert landscapes.' },
  { name: 'Lithuania',                                flag: 'lt', code: 'LT', description: 'Baltic nation known for history, culture, and nature.' },
  { name: 'Luxembourg',                               flag: 'lu', code: 'LU', description: 'Small European nation and major global financial center.' },
  { name: 'Madagascar',                               flag: 'mg', code: 'MG', description: 'Island nation renowned for unique wildlife and biodiversity.' },
  { name: 'Malawi',                                   flag: 'mw', code: 'MW', description: 'Southeast African country centered around Lake Malawi.' },
  { name: 'Malaysia',                                 flag: 'my', code: 'MY', description: 'Southeast Asian nation known for diversity and rainforests.' },
  { name: 'Maldives',                                 flag: 'mv', code: 'MV', description: 'Indian Ocean island nation famous for luxury resorts.' },
  { name: 'Mali',                                     flag: 'ml', code: 'ML', description: 'Historic West African nation known for ancient empires.' },
  { name: 'Malta',                                    flag: 'mt', code: 'MT', description: 'Mediterranean island nation rich in history and culture.' },
  { name: 'Marshall Islands',                         flag: 'mh', code: 'MH', description: 'Pacific island nation consisting of coral atolls.' },
  { name: 'Mauritania',                               flag: 'mr', code: 'MR', description: 'Desert nation where the Sahara meets the Atlantic.' },
  { name: 'Mauritius',                                flag: 'mu', code: 'MU', description: 'Tropical island nation known for beaches and diversity.' },
  { name: 'Mexico',                                   flag: 'mx', code: 'MX', description: 'North American nation rich in culture and heritage.' },
  { name: 'Micronesia',                               flag: 'fm', code: 'FM', description: 'Pacific island nation spread across numerous islands.' },
  { name: 'Monaco',                                   flag: 'mc', code: 'MC', description: 'Luxury Mediterranean city-state famous for casinos and yachts.' },
  { name: 'Mongolia',                                 flag: 'mn', code: 'MN', description: 'Vast landlocked nation known for steppes and nomadic culture.' },
  { name: 'Montenegro',                               flag: 'me', code: 'ME', description: 'Balkan nation featuring mountains and Adriatic coastline.' },
  { name: 'Morocco',                                  flag: 'ma', code: 'MA', description: 'North African country blending Arab, Berber, and European influences.' },
  { name: 'Mozambique',                               flag: 'mz', code: 'MZ', description: 'East African nation with a long Indian Ocean coastline.' },
  { name: 'Myanmar',                                  flag: 'mm', code: 'MM', description: 'Southeast Asian nation known for temples and traditions.' },
  { name: 'Namibia',                                  flag: 'na', code: 'NA', description: 'Southern African country famed for deserts and wildlife.' },
  { name: 'Nauru',                                    flag: 'nr', code: 'NR', description: "World's smallest independent island republic in the Pacific." },
  { name: 'Nepal',                                    flag: 'np', code: 'NP', description: 'Himalayan nation home to Mount Everest and rich culture.' },
  { name: 'Netherlands',                              flag: 'nl', code: 'NL', description: 'European country known for canals, tulips, and innovation.' },
  { name: 'New Zealand',                              flag: 'nz', code: 'NZ', description: 'Pacific nation famous for stunning natural landscapes.' },
  { name: 'Nicaragua',                                flag: 'ni', code: 'NI', description: 'Central American country known for lakes and volcanoes.' },
  { name: 'Niger',                                    flag: 'ne', code: 'NE', description: 'West African nation largely covered by the Sahara Desert.' },
  { name: 'Nigeria',                                  flag: 'ng', code: 'NG', description: "Africa's most populous nation and economic powerhouse." },
  { name: 'Niue',                                     flag: 'nu', code: 'NU', description: 'Self-governing Pacific island known for natural beauty.' },
  { name: 'North Macedonia',                          flag: 'mk', code: 'MK', description: 'Balkan nation rich in history and mountain scenery.' },
  { name: 'Norway',                                   flag: 'no', code: 'NO', description: 'Scandinavian country famous for fjords and high living standards.' },
  { name: 'Oman',                                     flag: 'om', code: 'OM', description: 'Arabian nation known for deserts and maritime heritage.' },
  { name: 'Pakistan',                                 flag: 'pk', code: 'PK', description: 'South Asian nation with diverse geography and cultures.' },
  { name: 'Palau',                                    flag: 'pw', code: 'PW', description: 'Pacific island nation renowned for marine biodiversity.' },
  { name: 'Panama',                                   flag: 'pa', code: 'PA', description: 'Central American country connecting two continents via canal.' },
  { name: 'Papua New Guinea',                         flag: 'pg', code: 'PG', description: 'Diverse Pacific nation with hundreds of ethnic groups.' },
  { name: 'Paraguay',                                 flag: 'py', code: 'PY', description: 'Landlocked South American country with rich cultural traditions.' },
  { name: 'Peru',                                     flag: 'pe', code: 'PE', description: 'South American nation home to Machu Picchu and Andes.' },
  { name: 'Philippines',                              flag: 'ph', code: 'PH', description: 'Archipelago nation known for beaches and cultural diversity.' },
  { name: 'Poland',                                   flag: 'pl', code: 'PL', description: 'Central European nation rich in history and resilience.' },
  { name: 'Portugal',                                 flag: 'pt', code: 'PT', description: 'Iberian nation known for explorers and Atlantic coastlines.' },
  { name: 'Qatar',                                    flag: 'qa', code: 'QA', description: 'Wealthy Gulf nation with modern infrastructure and energy resources.' },
  { name: 'Republic of Korea',                        flag: 'kr', code: 'KR', description: 'Advanced East Asian nation known for technology and culture.' },
  { name: 'Republic of Moldova',                      flag: 'md', code: 'MD', description: 'Eastern European country known for vineyards and traditions.' },
  { name: 'Romania',                                  flag: 'ro', code: 'RO', description: 'European nation famous for Transylvania and medieval heritage.' },
  { name: 'Russian Federation',                       flag: 'ru', code: 'RU', description: "World's largest country spanning Europe and Asia." },
  { name: 'Rwanda',                                   flag: 'rw', code: 'RW', description: 'East African nation known for conservation and development.' },
  { name: 'Saint Kitts and Nevis',                    flag: 'kn', code: 'KN', description: 'Caribbean twin-island nation known for tourism and beaches.' },
  { name: 'Saint Lucia',                              flag: 'lc', code: 'LC', description: 'Caribbean island famous for the iconic Piton mountains.' },
  { name: 'Saint Vincent and the Grenadines',         flag: 'vc', code: 'VC', description: 'Caribbean nation comprising islands and scenic coastlines.' },
  { name: 'Samoa',                                    flag: 'ws', code: 'WS', description: 'Polynesian island nation preserving strong cultural traditions.' },
  { name: 'San Marino',                               flag: 'sm', code: 'SM', description: 'Ancient microstate completely surrounded by Italy.' },
  { name: 'Sao Tome and Principe',                    flag: 'st', code: 'ST', description: 'Equatorial island nation known for cocoa and biodiversity.' },
  { name: 'Saudi Arabia',                             flag: 'sa', code: 'SA', description: 'Largest Arabian nation and birthplace of Islam.' },
  { name: 'Senegal',                                  flag: 'sn', code: 'SN', description: 'West African country known for culture and Atlantic coastline.' },
  { name: 'Serbia',                                   flag: 'rs', code: 'RS', description: 'Balkan nation with rich history and diverse landscapes.' },
  { name: 'Seychelles',                               flag: 'sc', code: 'SC', description: 'Indian Ocean archipelago famous for pristine beaches.' },
  { name: 'Sierra Leone',                             flag: 'sl', code: 'SL', description: 'West African nation known for beaches and resilience.' },
  { name: 'Singapore',                                flag: 'sg', code: 'SG', description: 'Global financial hub renowned for innovation and efficiency.' },
  { name: 'Slovakia',                                 flag: 'sk', code: 'SK', description: 'Central European country known for mountains and castles.' },
  { name: 'Slovenia',                                 flag: 'si', code: 'SI', description: 'Alpine nation celebrated for lakes, caves, and nature.' },
  { name: 'Solomon Islands',                          flag: 'sb', code: 'SB', description: 'Pacific island nation with rich marine and cultural heritage.' },
  { name: 'Somalia',                                  flag: 'so', code: 'SO', description: "Horn of Africa nation with Africa's longest mainland coastline." },
  { name: 'South Africa',                             flag: 'za', code: 'ZA', description: 'Diverse African nation known for wildlife and natural beauty.' },
  { name: 'South Sudan',                              flag: 'ss', code: 'SS', description: 'Young African nation rich in cultural diversity.' },
  { name: 'Spain',                                    flag: 'es', code: 'ES', description: 'European nation famous for history, culture, and tourism.' },
  { name: 'Sri Lanka',                                flag: 'lk', code: 'LK', description: 'Indian Ocean island known for tea and heritage sites.' },
  { name: 'Sudan',                                    flag: 'sd', code: 'SD', description: 'Nile-linked African nation with ancient historical roots.' },
  { name: 'Suriname',                                 flag: 'sr', code: 'SR', description: 'South American country known for rainforests and diversity.' },
  { name: 'Sweden',                                   flag: 'se', code: 'SE', description: 'Scandinavian nation recognized for innovation and sustainability.' },
  { name: 'Switzerland',                              flag: 'ch', code: 'CH', description: 'Alpine nation renowned for banking, watches, and neutrality.' },
  { name: 'Syrian Arab Republic',                     flag: 'sy', code: 'SY', description: 'Historic Middle Eastern nation with ancient civilizations.' },
  { name: 'Tajikistan',                               flag: 'tj', code: 'TJ', description: 'Mountainous Central Asian country dominated by the Pamirs.' },
  { name: 'Thailand',                                 flag: 'th', code: 'TH', description: 'Southeast Asian nation known for beaches and culture.' },
  { name: 'Timor-Leste',                              flag: 'tl', code: 'TL', description: 'Young Southeast Asian nation with Portuguese influences.' },
  { name: 'Togo',                                     flag: 'tg', code: 'TG', description: 'West African country with coastal plains and hills.' },
  { name: 'Tonga',                                    flag: 'to', code: 'TO', description: 'Polynesian kingdom spread across Pacific islands.' },
  { name: 'Trinidad and Tobago',                      flag: 'tt', code: 'TT', description: 'Caribbean nation famous for Carnival and energy resources.' },
  { name: 'Tunisia',                                  flag: 'tn', code: 'TN', description: 'North African nation blending Mediterranean and desert heritage.' },
  { name: 'Turkiye',                                  flag: 'tr', code: 'TR', description: 'Transcontinental nation bridging Europe and Asia.' },
  { name: 'Turkmenistan',                             flag: 'tm', code: 'TM', description: 'Central Asian nation known for deserts and gas reserves.' },
  { name: 'Tuvalu',                                   flag: 'tv', code: 'TV', description: 'Small Pacific island nation vulnerable to rising sea levels.' },
  { name: 'Uganda',                                   flag: 'ug', code: 'UG', description: 'East African nation known for lakes and wildlife.' },
  { name: 'Ukraine',                                  flag: 'ua', code: 'UA', description: 'Eastern European nation rich in agriculture and history.' },
  { name: 'United Republic of Tanzania',              flag: 'tz', code: 'TZ', description: 'East African nation home to Serengeti and Kilimanjaro.' },
  { name: 'Uruguay',                                  flag: 'uy', code: 'UY', description: 'South American nation known for stability and quality of life.' },
  { name: 'Uzbekistan',                               flag: 'uz', code: 'UZ', description: 'Central Asian nation rich in Silk Road heritage.' },
  { name: 'Vanuatu',                                  flag: 'vu', code: 'VU', description: 'Pacific island nation known for volcanoes and coral reefs.' },
  { name: 'Venezuela',                                flag: 've', code: 'VE', description: 'South American nation home to Angel Falls.' },
  { name: 'Vietnam',                                  flag: 'vn', code: 'VN', description: 'Southeast Asian nation known for history and scenic landscapes.' },
  { name: 'Yemen',                                    flag: 'ye', code: 'YE', description: 'Arabian nation with ancient history and cultural heritage.' },
  { name: 'Zambia',                                   flag: 'zm', code: 'ZM', description: 'Southern African nation famous for Victoria Falls.' },
  { name: 'Zimbabwe',                                 flag: 'zw', code: 'ZW', description: 'African nation known for wildlife and Great Zimbabwe ruins.' },
];

async function seedCountries() {
  await connectDB();
  console.log('Connected to MongoDB');

  let inserted = 0;
  let skipped = 0;

  for (const c of countries) {
    const result = await Country.updateOne(
      { name: c.name },
      {
        $setOnInsert: {
          ...c,
          slug: slugify(c.name),
          isActive: true,
          showOnWebsite: false,
          images: [],
          webContent: {
            overview: '',
            requirements: '',
            processingInfo: '',
            tips: '',
            faqs: [],
          },
        },
      },
      { upsert: true }
    );
    if (result.upsertedCount) inserted++;
    else skipped++;
  }

  console.log(`Done: ${inserted} inserted, ${skipped} already existed`);
  process.exit(0);
}

seedCountries().catch((err) => {
  console.error(err);
  process.exit(1);
});
